# Generated by Django 5.0.2 on 2024-05-18 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='MedicalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название медицинского учреждения')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Медицинское учреждение',
                'verbose_name_plural': 'Медицинские учреждения',
            },
        ),
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название линии метро')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер линии метро')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет линии метро')),
            ],
            options={
                'verbose_name': 'Линия метро',
                'verbose_name_plural': 'Линии метро',
            },
        ),
        migrations.CreateModel(
            name='ResearchMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Материал исследования',
                'verbose_name_plural': 'Материалы исследования',
            },
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название станции метро')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Долгота')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthLab_Navigator_api.metroline', verbose_name='Линия метро')),
            ],
            options={
                'verbose_name': 'Станция метро',
                'verbose_name_plural': 'Станции метро',
            },
        ),
        migrations.CreateModel(
            name='MedicalInstitutionBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной филиал')),
                ('working_hours', models.JSONField(blank=True, null=True, verbose_name='Рабочие часы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Долгота')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на филиал')),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Адрес')),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthLab_Navigator_api.medicalinstitution', verbose_name='Медицинское учреждение')),
                ('metro_stations', models.ManyToManyField(blank=True, to='HealthLab_Navigator_api.metrostation', verbose_name='Станции метро')),
            ],
            options={
                'verbose_name': 'Филиал медицинского учреждения',
                'verbose_name_plural': 'Филиалы медицинского учреждения',
            },
        ),
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('name', models.CharField(max_length=200, verbose_name='Название медицинской услуги')),
                ('main_description', models.TextField(default='', verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания системы')),
                ('government_code_804n', models.JSONField(blank=True, null=True, verbose_name='Коды услуги по 804н')),
                ('research_material', models.ManyToManyField(blank=True, related_name='research_material', to='HealthLab_Navigator_api.researchmaterial', verbose_name='Материалы исследования')),
            ],
            options={
                'verbose_name': 'Медицинская услуга',
                'verbose_name_plural': 'Медицинские услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceInMedicalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_available_oms', models.BooleanField(default=False, verbose_name='Доступно по ОМС')),
                ('is_available_dms', models.BooleanField(default=False, verbose_name='Доступно по ДМС')),
                ('is_available_at_home', models.BooleanField(default=False, verbose_name='Доступно на дому')),
                ('is_available_fast_result', models.BooleanField(default=False, verbose_name='Доступно при скором результате')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('price_for_fast_result', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена при скором результате')),
                ('price_for_at_home', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена на дому')),
                ('time_to_complete', models.DurationField(blank=True, null=True, verbose_name='Время выполнения')),
                ('time_to_complete_for_fast_result', models.DurationField(blank=True, null=True, verbose_name='Время выполнения при скором результате')),
                ('internal_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Внутренний код услуги')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на услугу')),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthLab_Navigator_api.medicalinstitution', verbose_name='Медицинское учреждение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthLab_Navigator_api.medicalservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Медицинское учреждение в услуге',
                'verbose_name_plural': 'Медицинские учреждения в услугах',
                'unique_together': {('service', 'medical_institution')},
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой'), ('unknown', 'Неизвестно')], default='unknown', max_length=20, verbose_name='Пол')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitingServiceInMedicalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания визита')),
                ('service_in_medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthLab_Navigator_api.serviceinmedicalinstitution', verbose_name='Услуга')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещение услуги на стр мед учреждения',
                'verbose_name_plural': 'Посещения услуг на стр мед учреждения',
            },
        ),
        migrations.CreateModel(
            name='VisitingMedicalInstitutionBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания визита')),
                ('medical_institution_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthLab_Navigator_api.medicalinstitutionbranch', verbose_name='Филиал мед учреждения')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещение филиала мед учреждения',
                'verbose_name_plural': 'Посещения филиалов мед учреждения',
            },
        ),
        migrations.CreateModel(
            name='VisitingMedicalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания визита')),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthLab_Navigator_api.medicalinstitution', verbose_name='Мед учреждение')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещение мед учреждения',
                'verbose_name_plural': 'Посещения мед учреждения',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='MedicalAgentOfMedicalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthLab_Navigator_api.medicalinstitution', verbose_name='Медицинское учреждение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Агент медицинского учреждения',
                'verbose_name_plural': 'Агенты медицинских учреждений',
            },
        ),
    ]
