# Generated by Django 5.0.2 on 2024-04-14 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthLab_Navigator_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HealthLab_Navigator_api.phone', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='only_some_for_branches',
            field=models.ManyToManyField(blank=True, to='HealthLab_Navigator_api.medicalinstitutionbranch', verbose_name='Филиалы'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='only_some_for_services',
            field=models.ManyToManyField(blank=True, to='HealthLab_Navigator_api.serviceinmedicalinstitution', verbose_name='Услуги'),
        ),
    ]
