# Generated by Django 5.0.2 on 2024-04-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthLab_Navigator_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание номера телефона'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='research_systems',
            field=models.ManyToManyField(blank=True, null=True, to='HealthLab_Navigator_api.researchmedicalsystem', verbose_name='Системы исследования'),
        ),
    ]
