# Generated by Django 5.0.2 on 2024-04-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthLab_Navigator_api', '0004_customuser_is_medical_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Материал исследования',
                'verbose_name_plural': 'Материалы исследования',
            },
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='research_systems',
            field=models.ManyToManyField(blank=True, to='HealthLab_Navigator_api.researchmedicalsystem', verbose_name='Системы исследования'),
        ),
    ]
