# Generated by Django 5.0.2 on 2024-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthLab_Navigator_api', '0005_researchmaterial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalservice',
            name='research_material',
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='research_material',
            field=models.ManyToManyField(blank=True, related_name='research_material', to='HealthLab_Navigator_api.researchmaterial', verbose_name='Материалы исследования'),
        ),
    ]
