# Generated by Django 5.0.2 on 2024-04-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthLab_Navigator_api', '0006_remove_medicalservice_research_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchmaterial',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
    ]
