# Generated by Django 5.0.2 on 2024-04-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthLab_Navigator_api', '0007_alter_researchmaterial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinstitutionbranch',
            name='latitude',
            field=models.CharField(default=0, max_length=50, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalinstitutionbranch',
            name='longitude',
            field=models.CharField(default=0, max_length=50, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalinstitutionbranch',
            name='working_hours',
            field=models.JSONField(verbose_name='Рабочие часы'),
        ),
    ]
