# Generated by Django 5.0.2 on 2024-04-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthLab_Navigator_api', '0008_medicalinstitutionbranch_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinstitutionbranch',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на филиал'),
        ),
    ]
