# Generated by Django 5.0.2 on 2024-04-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthLab_Navigator_api', '0009_medicalinstitutionbranch_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='visiting',
            options={'verbose_name': 'Визит', 'verbose_name_plural': 'Визиты'},
        ),
        migrations.AlterField(
            model_name='serviceinmedicalinstitution',
            name='time_to_complete',
            field=models.DurationField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='serviceinmedicalinstitution',
            name='time_to_complete_for_fast_result',
            field=models.DurationField(blank=True, null=True, verbose_name='Время выполнения при скором результате'),
        ),
    ]
