# Generated by Django 5.0.2 on 2024-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthLab_Navigator_api', '0017_remove_medicalinstitution_main_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinstitutionbranch',
            name='working_hours',
            field=models.JSONField(blank=True, null=True, verbose_name='Рабочие часы'),
        ),
    ]
